### PR TITLE
Add react to project

### PR DESCRIPTION
**Pull request by AshleyStauffer**
To use React you must have node version 8.10 or greater. Once you have that, to start running the app, navigate into the webapp folder and run "npm start." It should begin running live in localhost:3000 and making changes to App.js should show immediately after saving.

### CODE REVIEW

**Comment by Frank-Pasqualini** [comment]
Its probably a good idea to go over this Friday at standup or Thursday after class because the rest of us don't have much experience in React and we need to make sure it integrates cleanly or if we'll have to restructure the project.

**Comment by Frank-Pasqualini** [comment]
How does this format work @AshleyStauffer ? I based it off of https://andrew-flower.com/blog/Spring-Boot-and-React-1

**Comment by AshleyStauffer** [comment]
I've never used anything like this before so I'm not sure. How do you start the app with this setup? @Frank-Pasqualini

**Comment by Frank-Pasqualini** [comment]
> I've never used anything like this before so I'm not sure. How do you start the app with this setup? @Frank-Pasqualini

./gradlew bootRun will launch the site at localhost:8080.  It wont automatically refresh though I don't think.

But this way ./gradlew build will compile the entire project.  This just seemed like an easy to implement method, I'm not super sold on it and I'd be willing to switch if we found something better.

**Comment by AshleyStauffer** [comment]
I think I might find issue with the fact that you have to rebuild every single time you make a change. A typical setup for react allows for instant changes in the localhost when you save a file

**Comment by Frank-Pasqualini** [comment]
I am looking into alternate setups and https://github.com/arnaud-deprez/spring-boot-react-sample seems promising.

**Comment by AshleyStauffer** [comment]
@Frank-Pasqualini  I was looking at that one too and I agree that it looks better. Create-react-app is what I had initially done, so that would likely be a better setup

**Comment by Frank-Pasqualini** [comment]
See https://github.com/Frank-Pasqualini/JamBox/pull/6

**Pull request closed without merging**
